[package]
name = "rust-draw"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = "0.3.1"
dioxus-desktop = "0.3.0"
log = "0.4.17"
regex = "1.7.1"
